server_url: ''
incrementalbuild_url: 'https://webhook.gatsbyjs.com/hooks/benchmarks/publish/drupal/8192/63d645d7-d12c-4eda-bd67-fc62ec3e46d8,https://webhook.staging.gtsb.io/hooks/benchmarks/publish/drupal/8192/63d645d7-d12c-4eda-bd67-fc62ec3e46d8'
build_published: 1
preview_entity_types:
  node: node
  block_content: 0
  comment: 0
  contact_message: 0
  file: 0
  path_alias: 0
  shortcut: 0
  taxonomy_term: 0
  user: 0
  menu_link_content: 0
secret_key: ''
legacy_preview_url: 0
